// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pizza_Site.Models;

#nullable disable

namespace Pizza_Site.Migrations
{
    [DbContext(typeof(PizzaContext))]
    [Migration("20240920223244_IdDeleted")]
    partial class IdDeleted
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("Pizza_Site.Models.PizzaUsers", b =>
                {
                    b.Property<string>("User_Name")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Is_Admin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("User_Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("User_Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("User_MobileNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("User_Password")
                        .HasColumnType("TEXT");

                    b.HasKey("User_Name");

                    b.ToTable("PizzaStore");
                });

            modelBuilder.Entity("Pizza_Site.Models.PizzasDescription", b =>
                {
                    b.Property<string>("PizzaName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ingredients")
                        .HasColumnType("TEXT");

                    b.Property<int>("Price")
                        .HasColumnType("INTEGER");

                    b.HasKey("PizzaName");

                    b.ToTable("PizzasDescription");
                });
#pragma warning restore 612, 618
        }
    }
}
