// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pizza_Site.Models;

#nullable disable

namespace Pizza_Site.Migrations
{
    [DbContext(typeof(PizzaContext))]
    partial class PizzaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("Pizza_Site.Models.PizzaUsers", b =>
                {
                    b.Property<string>("User_Name")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Is_Admin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("User_Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("User_Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("User_MobileNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("User_Password")
                        .HasColumnType("TEXT");

                    b.HasKey("User_Name");

                    b.ToTable("PizzaStore", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
